# Generated by Django 5.1.4 on 2024-12-08 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area_professor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcoes',
            name='explicacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questoes',
            name='explicacao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
