# Generated by Django 5.1.4 on 2024-12-08 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area_professor', '0002_alter_opcoes_explicacao_alter_questoes_explicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respostasimulado',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='area_professor.turmas'),
        ),
    ]
